---
name: "pre-release-ubuntu"

on:
  push:
    branches:
      - "release"
    tags-ignore:
      - "*"

jobs:
  gh_pre_release:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.4.0"

      - name: "Install uv"
        uses: "astral-sh/setup-uv@v1"
        with:
          version: "latest"

      - run: "make install"
      - run: "make test"
      - run: "make build"
      - run: "ls dist/"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-ubuntu"
          prerelease: true
          title: "Development Build Ubuntu"
          files: |
            dist/*
#            potemkeys/*.jsonc
        id: "automatic_releases_ubuntu"
