---
name: "run-tests"

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.4.0"

      - run: "make install"
      - run: "make test-lcov"
      - run: "make test-tui"

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}